export class BusinessListing {
     
    constructor(
    public firstName='',
    public lastName='',
    public category='',
    public subCategory='',
    public floorDoorNumber='',
    public buildingName='',
    public landmark='',
    public streetName='',
    public nearestTown='',
    public district='',
    public zipCode='',
    public province='',
    public country='',
    public keyWords='',
    public openingTime='',
    public closingTime='',
    public workingDays='',
    public personName='',
    public mobile='',
    public designation='',
    public email='',
    public aboutDescription='',
    public facebookLink='',
    public instagramLink='',
    public twitterLink='',
    public whatsappNumber='',
    public youtubeLink='',
    public websiteLink='',
    public vedio='',
    public qr='',
    public caption='',
    public item='',
    public cat='',
    public subcat='',
    public price='',
    public desc='',
    public brname='',
    public brlocation='',
    public condet='',
    public title='',
    public descr='',
    public title1='',
    public descr1='',
    public job='',
    public salary='',
    public quali='',
    public tags='',
    public medias='',
    public url='',
    public publicUrl='',
    public userId=''

    ){}
  }